Ot96 169/organizacion
alkemyTech/OT-96-Server pull request #100
Opened 2021-11-17 15:59 UTC by Igabri3l

agregado de los links de las redes sociales al response

2021-11-18 01:23 UTC, manuelfrancisco requested changes

2021-11-18 01:23 UTC, manuelfrancisco commented on routes/organization.js
> +organizationRouter.put(
Revertir esto, tiene que ser un post

2021-11-19 00:57 UTC, manuelfrancisco approved these changes

2021-11-19 02:20 UTC, MatiasPreiti approved these changes

2021-11-19 02:20 UTC, merged

2026-03-07 22:19 UTC, Igabr13l commented
buenas