Ot96/186 list comment by news
alkemyTech/OT-96-Server pull request #102
Opened 2021-11-18 21:45 UTC by MatiasPreiti

- endpoint GetCommentsByNewsId

2021-11-18 22:05 UTC, Aleex1237 submitted a review, later dismissed

2021-11-18 22:11 UTC, aa-avila requested changes
Hay un comentario en routes (middleware)

2021-11-18 22:11 UTC, aa-avila commented on routes/news.js
> +newsRouter.get('/:id/comments', newsController.getCommentByNewsId);
no necesita middleware isAdmin?

2021-11-18 22:54 UTC, MatiasPreiti commented on routes/news.js
> +newsRouter.get('/:id/comments', newsController.getCommentByNewsId);
no, dice como usuario

2021-11-19 01:05 UTC, manuelfrancisco requested changes

2021-11-19 01:05 UTC, manuelfrancisco commented on controllers/news.js
> +const getCommentByNewsId = async (req, res, next) => {
comments en plural

2021-11-19 01:05 UTC, manuelfrancisco commented on repositories/news.js
> +  const response = await db.News.findAll({
usar un findByPk con el include, lo de los attributes reducidos es opcional

2021-11-19 01:05 UTC, manuelfrancisco commented on services/news.js
> +  const comments = await newsRepository.getCommentByNewsId(id);
acá recibirías una novelty (novedad)

2021-11-19 01:05 UTC, manuelfrancisco commented on services/news.js
> +  return comments;
y acá habría que devolver novelty.Comments

2021-11-19 18:41 UTC, aa-avila approved these changes

2021-11-20 00:18 UTC, manuelfrancisco approved these changes

2021-11-20 00:18 UTC, merged