Ot96 145
alkemyTech/OT-96-Server pull request #32
Opened 2021-11-02 16:47 UTC by Igabri3l

endpoint de creacion de categorias

2021-11-02 23:39 UTC, manuelfrancisco approved these changes

2021-11-02 23:39 UTC, manuelfrancisco commented on middlewares/validateCategoryDetails.js
> +  if(name === undefined) return res.status(400).json({
Una tontería pero fijate de usar Prettier, o prestarle atención a cómo queda el código, para que esté limpito

2021-11-02 23:39 UTC, manuelfrancisco commented on middlewares/validateCategoryDetails.js
> +  if(name === undefined) return res.status(400).json({
Esta validación se puede hacer directamente así: `if (!name)`

2021-11-02 23:39 UTC, manuelfrancisco requested changes
Aprobé sin querer perdón ajaja

2021-11-03 21:38 UTC, manuelfrancisco requested changes

2021-11-03 21:38 UTC, manuelfrancisco commented on controllers/categories.js
> +    if (!response) {
En vez de validar esto acá, sería mejor levantar un error desde el servicio

2021-11-03 21:38 UTC, manuelfrancisco commented on controllers/categories.js
> +      res.status(400).json({ ok: false, msg: "categoria repetida" });
En el documento de buenas prácticas se acordó usar el método next para handlear errores

2021-11-03 21:38 UTC, manuelfrancisco commented on services/categories.js
> +  if (res) return false;
Acá en vez de devolver false convendría tirar un error.
Para que quede claro para el futuro:
El controller es la instancia donde se atrapan los errores y se manejan (en este caso definimos en la retro que va a ser mediante el método next).
Por lo tanto, en todos los módulos que sean consumidos directa o indirectamente por el controller son los que los generan.
Poneme un pulgarcito arriba si está claro o consultame lo que necesites.

2021-11-03 21:39 UTC, manuelfrancisco commented
No olvides de resolver los conflictos

2021-11-03 21:55 UTC, Igabri3l commented on services/categories.js
> +  if (res) return false;
👍

2021-11-04 13:31 UTC, manuelfrancisco reviewed
Ojo con los conflictos

2021-11-04 19:21 UTC, manuelfrancisco approved these changes

2021-11-04 19:22 UTC, merged