actualizacion de usuario
alkemyTech/OT-96-Server pull request #37
Opened 2021-11-03 01:28 UTC by pancholi1

Se creo el endpoint para actualizar un usuario y se acomodo el user de app que estaba en  plural

2021-11-03 21:56 UTC, manuelfrancisco requested changes
**IMPORTANTE**: Vas a observar que te mencioné en un par de comentarios si el branch que creaste está hecho con la última versión de master. Si tenés dificultades para normalizarlo me avisás, pero sería tan sencillo como hacer un merge desde master hasta tu branch y resolver los conflictos.

2021-11-03 21:56 UTC, manuelfrancisco commented on app.js
> +app.use('/user', userRouter);
Tanto la ruta como la constante del router estaban bien como estaban

2021-11-03 21:56 UTC, manuelfrancisco commented on package-lock.json
>        "name": "ong-server",
Este archivo en teoría debería estar en el gitignore para que no se suba, serguro que hiciste un branch con la última versión de master?

2021-11-03 21:56 UTC, manuelfrancisco commented on routes/users.js
> +const { Router } = require('express');
En este archivo hay un conflicto, vuelvo a insistir en si creaste el branch con la última versión de master.

2021-11-03 23:15 UTC, pancholi1 commented
Creo que ahi esta manu, sino mañana nos conectamos y me explicas como es

2021-11-04 13:50 UTC, manuelfrancisco commented
Sigue estando desactualizado con lo de master, fijate de usar esta secuencia de comandos:
```
git checkout ActUser
git pull origin master
```

2021-11-04 23:41 UTC, manuelfrancisco approved these changes

2021-11-04 23:41 UTC, merged