Ot96 146/endpoint update category
alkemyTech/OT-96-Server pull request #38
Opened 2021-11-03 03:09 UTC by MatiasPreiti

-  Creacion de endpoint (/categories/:id) para update.
- Utilización de verificador de token y administrador en ruta

2021-11-03 22:11 UTC, manuelfrancisco requested changes

2021-11-03 22:11 UTC, manuelfrancisco commented on routes/categories.js
> +categoriesRouter.put('/:id', verifyToken, isAdmin, categoriesController.update);
Deberías usar el middleware de isOwnership en vez del verifyToken.
De paso estaría bueno cambiarle el nombre de isOwnership a isOwnedMember para dar más claridad. Implicaría cambiar todos los routes nomás porque sólo se usa ahí (o debería).

2021-11-03 22:11 UTC, manuelfrancisco commented on repositories/categories.js
>  // Get all categories
Ya que estamos te pido borrar los comenntarios innecesarios

2021-11-03 22:11 UTC, manuelfrancisco commented on repositories/categories.js
> +      exclude: ['description', 'deletedAt', 'createdAt', 'updatedAt'],
Sé que no hiciste este método pero estaría bueno que un getAll no tenga lógica de exlcluir columnas, debería ser trabajo: o del servicio, o de otro método en el repo con un nombre representativo

2021-11-03 22:11 UTC, manuelfrancisco commented on services/categories.js
> +      return {
En vez de return no debería ser throw new Error?

2021-11-03 22:11 UTC, manuelfrancisco commented on services/categories.js
> +    return {
Idem error 404

2021-11-04 00:24 UTC, MatiasPreiti commented
-deleting comments.
-error refactoring.
-isOwnedMember  implementation.

2021-11-04 13:12 UTC, manuelfrancisco approved these changes

2021-11-04 13:20 UTC, merged