Ot96 152
alkemyTech/OT-96-Server pull request #40
Opened 2021-11-03 18:23 UTC by Palmieri31

- add newsRouter to app.js
- add newController
- add newsRepository
- add newsRoutes
- encrypted password for user seeder
- add newsService
- fix verifyToken in security.js
- fix error req.status to res.status in auths middleware

2021-11-03 23:02 UTC, manuelfrancisco commented on seeders/20201109013159-create-demo-user.js
> +      password: '$2a$10$4hVG5w2RMM.P0ST64W2qC.jlrIaq7W09oTOwEq.UqxQ1vDZmaoaja',
Por qué está este cambio?

2021-11-03 23:06 UTC, Palmieri31 commented on seeders/20201109013159-create-demo-user.js
> +      password: '$2a$10$4hVG5w2RMM.P0ST64W2qC.jlrIaq7W09oTOwEq.UqxQ1vDZmaoaja',
lo había cambiado para loguearme y usar el middleware isAdmin para probar el remove de news

2021-11-04 13:43 UTC, manuelfrancisco commented on services/security.js
> +    return false;
Con qué objetivo se modificó todo esto?

2021-11-04 23:59 UTC, manuelfrancisco requested changes
Ojo con los conflictos

2021-11-05 11:32 UTC, closed without merging