Ot96 144/detalle categoria
alkemyTech/OT-96-Server pull request #42
Opened 2021-11-03 21:48 UTC by Aleex1237

- added categories.js Router & get a category route
-  add getById category method of Controller
- added getById category method on services & error handler
- added query getById category & fix import of model

2021-11-03 22:35 UTC, JCAlmazan reviewed
TEST PR MAL

2021-11-03 22:35 UTC, JCAlmazan approved these changes
TEST PR MAL 2

2021-11-03 23:57 UTC, manuelfrancisco requested changes

2021-11-03 23:57 UTC, manuelfrancisco commented on routes/categories.js
> +categoriesRouter.get('/:id',authMiddleware.verifyToken ,categoriesController.getById);
Hay que usar también el middleware de isAdmin, y en vez de verifyToken usar el que ahora se llama isOwnership (a Mati le dije que le cambie el nombre a isOwnedMember, ponete en contacto para ponerte más al corriente,  y asumí que ya está cambiado el nombre)

2021-11-04 13:36 UTC, manuelfrancisco submitted a review, later dismissed
Ojo con los conflictos

2021-11-04 22:35 UTC, manuelfrancisco requested changes

2021-11-04 23:59 UTC, manuelfrancisco approved these changes

2021-11-04 23:59 UTC, merged