add aws-sdk upload & download file
alkemyTech/OT-96-Server pull request #47
Opened 2021-11-04 04:11 UTC by aa-avila

- Added aws_s3.js to /services
- uploadFile(file)
- getFileStream(key)

2021-11-04 11:28 UTC, manuelfrancisco commented on package.json
> +    "bcryptjs": "^2.4.3",
Esta dependencia dónde se usa?

2021-11-04 11:28 UTC, manuelfrancisco commented on services/aws_s3.js
> +const s3 = new AWS.S3();
No te falta ponerle el access key y el secret access key?

2021-11-04 13:57 UTC, aa-avila commented on package.json
> +    "bcryptjs": "^2.4.3",
la verdad no quise introducir ese cambio, lo que quería hacer era incluir la librería aws-sdk. Eso otro debe venir de algún cambio que se hizo posterior a mi branch, la verdad no sé. Sugerís que revierta esto y sólo incluya aws-sdk?

2021-11-04 14:00 UTC, aa-avila commented on services/aws_s3.js
> +const s3 = new AWS.S3();
se pueden pasar dichos parámetros, pero no es necesario (se ve que al crear la instancia, internamente obtiene las variables de entorno, siempre y cuando estén correctamente nombradas). Si te parece mejor que sea más explícito, lo modifico.

2021-11-04 19:13 UTC, manuelfrancisco commented on services/aws_s3.js
> +const s3 = new AWS.S3();
Sí yo lo haría explícito, me parece más correcto. Obviamente obteniéndolas de las variables de entorno pero que sea explícito.

2021-11-04 21:58 UTC, manuelfrancisco approved these changes
Ojo con los conflictos

2021-11-04 23:57 UTC, manuelfrancisco requested changes

2021-11-04 23:57 UTC, manuelfrancisco commented on package.json
> +    "bcrypt": "^5.0.1",
Sigue figurando bycrypt a secas

2021-11-05 00:21 UTC, aa-avila commented on package.json
> +    "bcrypt": "^5.0.1",
ah es que tenia entendido que alguien lo usó ademas del bcryptjs y que despues iban a resolver eso. Ok lo saco

2021-11-05 01:00 UTC, manuelfrancisco approved these changes

2021-11-05 01:00 UTC, merged