Ot96 161/creacion slides
alkemyTech/OT-96-Server pull request #78
Opened 2021-11-11 00:03 UTC by Igabri3l

creación de endpoint createSlide con conexión a aws

2021-11-11 14:26 UTC, manuelfrancisco requested changes

2021-11-11 14:26 UTC, manuelfrancisco commented on services/aws_s3.js
> +    Key: 'image.png'
Me comentás por qué se hicieron estos cambios?

2021-11-11 14:26 UTC, manuelfrancisco commented on services/slides.js
> +  const { url } = await imageUploader.upload(image);
Recordaba que íbamos a guardar tanto la url como la key, puede ser?

2021-11-11 20:35 UTC, Igabri3l commented on services/slides.js
> +  const { url } = await imageUploader.upload(image);
`{
  ETag: '"0d633f622d7858287286cc645e9cf309"',
  Location: 'https://cohorte-octubre-e8bd4748.s3.amazonaws.com/image.png',
  key: 'image.png',
  Key: 'image.png',
  Bucket: 'cohorte-octubre-e8bd4748'
}`
es lo que devuelve aws_3.js. en location (url) se encuentra contenido el bucket y la key

2021-11-11 23:46 UTC, Igabri3l commented on services/aws_s3.js
> +    Key: 'image.png'
`const fileStream = fs.createReadStream(file.path)`
este metodo recibe un parametro que es la direccion de la imagen y devuelve un buffer que se utiliza en body. yo lo que mando en el parametro es el buffer de la imagen y se lo asigno a body de manera directa
en key recibe un string. por lo tanto decidi poner el texto del request

2021-11-12 01:54 UTC, manuelfrancisco approved these changes

2021-11-12 01:57 UTC, merged