Se realizo el seeders con 10 usuarios de prueba
alkemyTech/OT-96-Server pull request #95
Opened 2021-11-16 02:32 UTC by pancholi1

Se realizo un usuario para cada integrante de nuestro grupo

2021-11-16 22:23 UTC, manuelfrancisco requested changes

2021-11-16 22:23 UTC, manuelfrancisco commented on README.md
> +## Documentation Seeders Users
Le pondría de título Test users o algo así mejor

2021-11-16 22:23 UTC, manuelfrancisco commented on README.md
> +Each of us has an admin user and a standard user, for example:
Acá hay que poner todos los usuarios con su password y si son admin o no, quizás podés listar primero todos los usuarios admin y luego todos los standard, pero tienen que estar todos los usuarios para que sea de fácil acceso

2021-11-17 16:03 UTC, Igabri3l submitted a review, later dismissed

2021-11-18 00:48 UTC, manuelfrancisco requested changes

2021-11-18 00:48 UTC, manuelfrancisco commented on README.md
> +email: ManuelFrancisco@admin.com     password: ManuelFrancisco1  firstName:Manuel  lastName :Francisco
Faltan 3 usuarios admininstradores y 3 usuarios normales

2021-11-18 00:48 UTC, manuelfrancisco commented on seeders/20201109013159-create-demo-users.js
> +					firstName: 'Alexis',
A partir de este usuario parece que están todos planteados como standard pero tienen el mismo roleId que los administradores

2021-11-18 22:14 UTC, Aleex1237 requested changes

2021-11-18 22:14 UTC, Aleex1237 commented on README.md
> +=======
Faltó borrar este comentario

2021-11-18 22:14 UTC, Aleex1237 commented on seeders/20201109013159-create-demo-users.js
> +				},
Hay 11 usuarios administradores

2021-11-21 18:42 UTC, manuelfrancisco submitted a review, later dismissed

2021-11-21 18:46 UTC, aa-avila submitted a review, later dismissed

2021-11-21 20:25 UTC, MatiasPreiti approved these changes

2021-11-21 20:25 UTC, aa-avila approved these changes

2021-11-21 20:25 UTC, Aleex1237 approved these changes

2021-11-21 20:25 UTC, merged