Ot96/183 creacion comentario
alkemyTech/OT-96-Server pull request #97
Opened 2021-11-16 03:56 UTC by MatiasPreiti

-Endpoint de Creacion de Comentario

- Corrección en nombre de "newsId" en migración

2021-11-16 22:26 UTC, manuelfrancisco approved these changes
Ojo con los conflictos

2021-11-18 00:54 UTC, manuelfrancisco requested changes

2021-11-18 00:54 UTC, manuelfrancisco commented on services/comments.js
> +    const error = new Error('there was an error in member creation');
El mensaje de error hace relación a members en vez de comentarios

2021-11-18 01:10 UTC, manuelfrancisco approved these changes

2021-11-18 01:12 UTC, Aleex1237 approved these changes

2021-11-18 01:12 UTC, JCAlmazan approved these changes

2021-11-18 01:13 UTC, merged