Ot96 184/comments
alkemyTech/OT-96-Server pull request #99
Opened 2021-11-17 15:58 UTC by Igabri3l

agregado de actualizar comentarios

2021-11-18 01:20 UTC, manuelfrancisco requested changes

2021-11-18 01:20 UTC, manuelfrancisco commented on middlewares/auths.js
> +    if (comment.id === userFound.id) {
Acá debería comparar el userId del comment

2021-11-18 01:20 UTC, manuelfrancisco commented on services/comments.js
> +    const error = new Error('comments no encontrado.');
Comments está en plural y debería empezar en mayúscula. Además el mensaje debería estar en inglés completamente.

2021-11-19 00:56 UTC, manuelfrancisco approved these changes

2021-11-19 02:18 UTC, MatiasPreiti approved these changes

2021-11-19 02:18 UTC, merged